version: 2.1

parameters:

  schedule:
    type: boolean
    default: false

jobs:

  Echo message:
    parameters:
      message:
        type: string
        default: undefined
    docker:
      - image: cimg/base:2022.08
    steps:
      - run: "Echo: << parameters.message >>"

workflows:

  Regular workflow:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - Echo message:
          message: Regular workflow
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v([0-9]+){1}(\.[0-9]+){2}(\-.+)?/

  Scheduled workflow:
    when:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - Echo message:
          message: "Scheduled workflow"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v([0-9]+){1}(\.[0-9]+){2}(\-.+)?/
